### ISSUE TITLE
 2023-02-20: Jamming mitigation meeting #3

### ISSUE THREAD

**Issue by carlaKC** [ClaraShk/LNJamming#4]
Time: 19:00 UTC
Link to the call: https://meet.jit.si/UnjammingLN

Agenda:
1. Local reputation scoring

Please add proposed agenda items in the comments!

**Comment by ariard** [comment]
Yes local reputation scoring, pursuing subject from last time!

I think one more topic with implications on channel jamming:
2. Highly available channels (https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-February/003842.html)

I think keep building consensus between all the proposals gathered until now (unconditional fees, staking credentials, circuit breaker) and we can just give an update on how our research all is doing.

By the way, speaking at the Advancing Bitcoin conf on channel jamming (at 14:05 day 1 iirc) few weeks from now. I think I'll present on my old research stuff (https://jamming-dev.github.io/book/about.html) as it's already way ahead the curve of the knowledge state of a lot of people. Been invited for the 3rd time by the organisers (after 2020 and 2022).

**Comment by ariard** [comment]
Had a look on the write-up! Great, still have a conceptual issue on how local reputation scheme holds across periods where routing fees are fluctuating. E.g, Alice might have build a reputation of 1 with Bob during period of 1000 ppm however this reputation is used to jam Bob channels when gossiped routing fees have moved to 10000 ppm. And quantitative score instead of binary buckets sound more flexibility for fault-tolerance.

Looking forward to talk about it more during tomorrow meeting!

**Comment by ClaraShk** [comment]
As Alice's reputation is calculated back from the current time [t-L,t], and is in comparison to a window also ending at the current time [t-S,t], this would not be an issue as the threshold she needs to meet is constantly updated.
